### ISSUE TITLE
Errors loading with pf1 and 9.242

### ISSUE THREAD

**Issue by chris-sanders** [SvenWerlen/fvtt-data-toolbox#24]
I get the following error when I load up a character sheet and try to search a compendium for (pf-content). I never see the data toolbox overlay to re-submit changes.

```
foundry.js:316 TypeError: Cannot read properties of undefined (reading 'entity')
[Detected 2 packages: data-toolbox, system:pf1]
    at Function.hook (letscontribute.js:79:20)
    at letscontribute.js:65:73
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at ActorSheetPFCharacter._getHeaderButtons (foundry.js:3303:13)
    at ActorSheetPFCharacter._getHeaderButtons (foundry.js:4265:25)
    at ActorSheetPFCharacter._getHeaderButtons (foundry.js:47781:25)
    at ActorSheetPFCharacter._renderOuter (foundry.js:3188:27)
    at ActorSheetPFCharacter._render (foundry.js:3076:27)
    at async ActorSheetPFCharacter._render (foundry.js:3761:5)
    at async ActorSheetPFCharacter._render (base.js:2622:20)
onError @ foundry.js:316
🎁call_wrapped @ libWrapper-wrapper.js:510
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:186
_call @ foundry.js:298
call @ foundry.js:279
_getHeaderButtons @ foundry.js:3303
_getHeaderButtons @ foundry.js:4265
_getHeaderButtons @ foundry.js:47781
_renderOuter @ foundry.js:3188
_render @ foundry.js:3076
await in _render (async)
_render @ foundry.js:3761
_render @ base.js:2622
render @ foundry.js:3018
render @ foundry.js:4256
_onClickDocumentName @ foundry.js:47243
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by SvenWerlen** [comment]
Hi Chris,
I unfortunately had to stop maintaining and supporting the "Let's contribute" part of the module, as mentioned here :
https://github.com/SvenWerlen/fvtt-data-toolbox/issues/22#issuecomment-1013918159

I removed it from the latest V9-compatible release
